#Goblins vs Gnomes Set

def All():
  Cards=Minions()
  Cards+=Spells()
  Cards+=Weapons()
  return Cards

def Minions():
  #[class,mana cost,attack,health,text,tribe,name,rarity]
  Cards=[["Neutral",0,0,2,"Taunt","Mech","Target Dummy","Rare"],
         ["Neutral",1,1,2,"Has +2 Attack while you have a Mech.","","Cogmaster","Common"],
         ["Neutral",1,2,1,"Deathrattle: Add a Spare Part card to your hand.","Mech","Clockwork Gnome","Common"],
         ["Neutral",2,2,3,"Whenever your opponent casts a spell, gain +1 Attack.","","Stonesplinter Trogg","Common"],
         ["Neutral",2,2,3,"After you summon a Pirate, deal 2 damage to a random enemy.","","Ship's Cannon","Common"],
         ["Neutral",2,3,2,"Battlecry: Transform a friendly minion into a random minion with the same Cost.","","Recombobulator","Epic"],
         ["Neutral",2,3,2,"","Murloc","Puddlestomper","Common"],
         ["Neutral",2,1,2,"At the start of each turn, gain +1 Attack.","Mech","Micro Machine","Common"],
         ["Neutral",2,2,3,"Your Mechs cost (1) less.","Mech","Mechwarper","Common"],
         ["Neutral",2,2,3,"Stealth","","Gilblin Stalker","Common"],
         ["Neutral",2,1,1,"Deathrattle: Deal 2 damage to all minions.","Mech","Explosive Sheep","Common"],
         ["Neutral",2,1,2,"Taunt. Divine Shield.","Mech","Annoy-o-Tron","Common"],
         ["Neutral",3,3,3,"Battlecry: If you have a Mech, gain +1/+1 and add a Spare Part to your hand.","","Tinkertown Technician","Common"],
         ["Neutral",3,3,4,"","Mech","Spider Tank","Common"],
         ["Neutral",3,4,4,"50% chance to attack the wrong enemy.","","Ogre Brute","Common"],
         ["Neutral",3,2,3,"Taunt. Battlecry: Gain +1/+1 for each enemy Deathrattle minion.","","Lil' Excorcist","Rare"],
         ["Neutral",3,2,4,"If you control a Secret at the end of your turn, restore 4 Health to your hero.","","Illuminator","Rare"],
         ["Neutral",3,2,3,"Whenever you play a 1 Attack minion, gie it +2/+2.","","Hobgoblin","Epic"],
         ["Neutral",3,2,4,"Has +4 Attack while your opponent has 6 or more cards in hand.","","Goblin Sapper","Rare"],
         ["Neutral",3,3,2,"Battlecry: Draw a card. If it's a minion, transform it into a Chicken.","","Gnomish Experimenter","Rare"],
         ["Neutral",3,1,4,"Charge. Taunt.","","Gnomeregan Infantry","Common"],
         ["Neutral",3,1,4,"Windfury","Mech","Flying Machine","Common"],
         ["Neutral",4,4,3,"Deathrattle: Summon a random 2-Cost minion.","Mech","Piloted Shredder","Common"],
         ["Neutral",4,4,1,"Stealth. Spell Damage +1.","","Mini-Mage","Epic"],
         ["Neutral",4,4,5,"Deathrattle: Give each player a Spare Part.","Mech","Mechanical Yeti","Common"],
         ["Neutral",4,5,4,"","Beast","Lost Tallstrider","Common"],
         ["Neutral",4,4,3,"Battlecry: Take control of a random enemy Secret.","","Kezan Mystic","Rare"],
         ["Neutral",4,1,4,"At the end of each player's turn, that player draws until they have 3 cards.","Mech","Jeeves","Rare"],
         ["Neutral",4,3,2,"Battlecry: Give your other minions Windfury, Taunt or Divine Shield (at random).","Mech","Enhance-o Mechano","Epic"],
         ["Neutral",4,3,5,"Whenever your opponent casts a spell, gain +2 Attack.","","Burly Rockjaw Trogg","Common"],
         ["Neutral",4,2,5,"Taunt. Can't be targeted by spells or Hero Powers.","Mech","Arcane Nullifier","Rare"],
         ["Neutral",5,7,4,"","Pirate","Salty Dog","Common"],
         ["Neutral",5,4,5,"At the start of your turn, if you have at least 3 Mechs, destroy them all and form V-07-TR-0N.","Mech","Mimiron's Head","Legendary"],
         ["Neutral",5,5,4,"Battlecry: Deal 6 damage randomly split between all other characters.","","Madder Bomber","Rare"],
         ["Neutral",5,1,5,"Whenever a friendly Mech dies, gain +2/+2.","Mech","Junkbot","Epic"],
         ["Neutral",5,3,3,"Battlecry: Restore 8 Health to your hero.","Mech","Antique Healbot","Common"],
         ["Neutral",6,5,7,"Battlecry and Deathrattle: Add a Spare Part card to your hand.","","Toshley","Legendary"],
         ["Neutral",6,6,4,"Deathrattle: Summon a random 4-Cost minion.","Mech","Piloted Sky Golem","Epic"],
         ["Neutral",6,7,6,"All minions have a 50% chance to attack the wrong enemy.","","Mogor the Ogre","Legendary"],
         ["Neutral",6,3,6,"Whenever you cast a 1-mana spell, add a random Mech to your hand.","","Gazlowe","Legendary"],
         ["Neutral",7,6,6,"Whenever your opponent casts a spell, summon a Burly Rockjaw Trogg.","","Troggzor the Earthinator","Legendary"],
         ["Neutral",7,7,7,"Battlecry: Summon two 1/1 Boom Bots. Warning: Bots may explode.","","Dr. Boom","Legendary"],
         ["Neutral",8,5,7,"Deathrattle: Summon a random Legendary minion.","Mech","Sneed's Old Shredder","Legendary"],
         ["Neutral",8,7,7,"Divine Shield","Mech","Force-Tank MAX","Common"],
         ["Neutral",8,6,9,"Also damages the minion next to whomever he attacks.","Mech","Foe Reaper 4000","Legendary"],
         ["Neutral",9,9,7,"Whenever an enemy minion dies, summon a Leper Gnome.","Mech","Mekgineer Thermaplugg","Legendary"],
         ["Neutral",12,8,8,"Costs (1) less for each card in your opponent's hand.","Mech","Clockwork Giant","Epic"],
         ["Druid",2,2,2,"Taunt. Choose One- +1 Attack; or +1 Health.","Mech","Anodized Robo Cub","Common"],
         ["Druid",3,2,4,"Choose One- Give each player a Mana Crystal; or Each player draws a card.","","Grove Tender","Rare"],
         ["Druid",5,4,4,"Battlecry: If you have a Beast, transform this minion into a 7/7.","","Druid of the Fang","Common"],
         ["Druid",6,7,6,"Whenever this minion takes damage, add a Spare Part card to your hand.","Mech","Mech-Bear-Cat","Rare"],
         ["Druid",7,9,7,"Deathrattle: Shuffle this minion into your deck.","Beast","Malorne","Legendary"],
         ["Hunter",2,2,3,"Your Hero Power can target minions.","","Steamwheedle Sniper","Epic"],
         ["Hunter",3,3,3,"Battlecry: Give your other Mechs +2 Attack.","Mech","Metaltooth Leaper","Rare"],
         ["Hunter",5,2,6,"Taunt. Battlecry: Gain +1 Attack for each other Beast you have.","Beast","King of Beasts","Rare"],
         ["Hunter",7,6,9,"Whenever this minion takes damage, double it's Attack.","Beast","Gahz'rilla","Legendary"],
         ["Mage",2,2,3,"Freeze any character damaged by this minion.","Mech","Snowchugger","Common"],
         ["Mage",3,3,3,"Spell Damage +1","Mech","Soot Spewer","Rare"],
         ["Mage",4,2,5,"Adjacent minions can't be targeted by spells or Hero Powers.","","Wee Spellstopper","Epic"],
         ["Mage",4,5,4,"Battlecry: If you have a Mech, deal 4 damage randomly split among all enemies.","","Goblin Blastmage","Rare"],
         ["Mage",7,7,7,"When you draw this, deal 2 damage to all characters.","Mech","Flame Leviathan","Legendary"],
         ["Paladin",2,2,2,"Divine Shield","Mech","Shielded Minibot","Common"],
         ["Paladin",3,4,3,"Battlecry: Deal 2 damage to all minions with Deathrattle.","","Scarlet Purifier","Rare"],
         ["Paladin",5,2,5,"Battlecry: Give your Silver Hand Recruits +2/+2.","","Quartermaster","Epic"],
         ["Paladin",5,6,3,"Whenever you summon a Mech, gain Divine Shield.","Mech","Cobalt Guardian","Rare"],
         ["Paladin",5,1,7,"Whenever a friendly minion dies while this is in your hand, gain +1 Attack","","Bolvar Fordragon","Legendary"],
         ["Priest",1,2,1,"Battlecry: Deal 3 damage to each hero.","","Shadowbomber","Epic"],
         ["Priest",2,3,2,"Battlecry: Give a minion -2 Attack this turn.","","Shrinkmeister","Common"],
         ["Priest",2,2,3,"Whenever a character is healed, deal 1 damage to a random enemy.","Mech","Shadowboxer","Rare"],
         ["Priest",5,6,2,"Battlecry: Swap Health with another minion.","","Vol'jin","Legendary"],
         ["Priest",5,5,5,"Battlecry: Give a friendly Mech +4 Health.","Mech","Upgraded Repair Bot","Rare"],
         ["Rogue",2,4,1,"Whenever you summon a Pirate, gain Stealth.","Pirate","One-eyed Cheat","Rare"],
         ["Rogue",2,3,2,"Battlecry: Give your weapon +1 Attack.","Mech","Goblin Auto-Barber","Common"],
         ["Rogue",3,2,2,"At the end of your turn give another friendly Mech +2/+2.","Mech","Iron Sensei","Rare"],
         ["Rogue",5,6,6,"Stealth. 50% chance to attack the wrong enemy.","","Ogre Ninja","Rare"],
         ["Rogue",6,5,8,"Whenever your opponent casts a spell, gain a copy of it and give them a Coin.","","Trade Price Gallywix","Legendary"],
         ["Shaman",2,3,2,"Windfury","Mech","Whirling Zap-o-matic","Common"],
         ["Shaman",2,0,3,"At the end of your turn restore 4 Health to your hero.","Totem","Vitality Totem","Rare"],
         ["Shaman",4,2,5,"Whenever another friendly Murloc dies, draw a card. Overload: (1)","Murloc","Siltfin Spiritwalker","Epic"],
         ["Shaman",4,5,4,"Windfury, Overload: (1). 50% chance to attack the wrong enemy.","","Dunemaul Shaman","Rare"],
         ["Shaman",7,7,7,"Battlecry: Add 4 random Murlocs to your hand. Overload: (3)","","Neptulon","Legendary"],
         ["Warlock",2,1,4,"Whenever this minion deals damage, restore that much Health to your hero.","Demon","Mistress of Pain","Rare"],
         ["Warlock",4,3,5,"At the end of your turn deal 2 damage to a non-Mech minion.","Mech","Fel Cannon","Rare"],
         ["Warlock",5,4,4,"Whenever your hero takes damage on your turn, gain +2/+2.","Demon","Floating Watcher","Common"],
         ["Warlock",6,9,9,"At the end of each turn destroy this minion if it's your only one.","Mech","Anima Golem","Epic"],
         ["Warlock",9,9,7,"Your other Demons have +2/+2. Your hero is Immune.","Demon","Mal'Ganis","Legendary"],
         ["Warrior",1,1,3,"Enrage: +1 Attack.","Mech","Warbot","Common"],
         ["Warrior",4,2,5,"Battlecry: Give a friendly Mech +2/+2.","Mech","Screwjank Clunker","Rare"],
         ["Warrior",5,5,5,"Whenever you gain Armor, give this minion +1 Attack.","Mech","Siege Engine","Rare"],
         ["Warrior",6,5,5,"Battlecry: Gain 5 Armor.","","Shieldmaiden","Rare"],
         ["Warrior",6,6,5,"Battlecry: Shufle a Mine into your opponent's deck. When drawn, it explodes for 10 damage.","Mech","Iron Juggernaut","Legendary"]
    ]
  return Cards

def Spells():
  #[class,mana cost,text,name,rarity]
  Cards=[["Druid",6,"Shuffle an enemy minion into your opponent's deck.","Recycle","Rare"],
         ["Druid",6,"Choose One- Summon 5 Wisps; or Give a minion +5/+5 and Taunt.","Dark Wispers","Epic"],
         ["Druid",9,"Restore all characters to full Health.","Tree of Life","Epic"],
         ["Hunter",2,"Trigger all Deathrattles on your minions.","Feign Death","Epic"],
         ["Hunter",2,"Draw a card. If it's a Beast, it costs (4) less.","Call Pet","Rare"],
         ["Hunter",5,"Deal 3 damage to a minion and the enemy hero.","Cobra Shot","Common"],
         ["Mage",2,"Add a random minion to your hand. It costs (3) less.","Unstable Portal","Rare"],
         ["Mage",2,"Deal 4 damage to a random enemy minion.","Flamecannon","Common"],
         ["Mage",4,"Put a copy of each friendly minion into your hand.","Echo of Medivh","Epic"],
         ["Paladin",2,"Restore 4 Health to your hero and gain +4 Attack this turn.","Seal of Light","Common"],
         ["Paladin",3,"Summon three 1/1 Silver Hand Recruits. Equip a 1/4 Weapon.","Muster for Battle","Rare"],
         ["Priest",1,"Restore 3 Health. If the target is still damaged, summon a Lightwarden.","Light of the Naaru","Rare"],
         ["Priest",3,"Give a minion +2/+4 and Spell Damage +1.","Velen's Chosen","Common"],
         ["Priest",6,"Deal damage to each minion equal to its Attack.","Lightbomb","Epic"],
         ["Rogue",4,"Give your weapon +3 Attack. Combo: Give a random friendly minion +3 Attack.","Tinker's Sharpsword Oil","Common"],
         ["Rogue",4,"Destroy a random enemy minion. Combo: And your opponent's weapon.","Sabotage","Epic"],
         ["Shaman",2,"Deal 3-6 damage. Overload: (1)","Crackle","Common"],
         ["Shaman",4,"Put a random minion from each player's hand into the battlefield.","Ancestor's Call","Epic"],
         ["Warlock",2,"Deal 3 damage.","Darkbomb","Common"],
         ["Warlock",4,"Deal 2-4 damage to a minion. Summon a 1/1 Imp for each damage dealt.","Imp-losion","Rare"],
         ["Warlock",5,"Deal 5 damage to a minion. If it's a friendly Demon, Give it +5/+5 instead.","Demonheart","Epic"],
         ["Warrior",3,"Deal 1 damage to a random minion. Repeat until a minion dies.","Bouncing Blade","Epic"],
         ["Warrior",7,"Destroy a minion. If you have a damaged minion, this costs (4) less.","Crush","Epic"]
    ]
  return Cards

def Weapons():
  #[class,mana cost,attack,durability,text,name,rarity]
  Cards=[["Hunter",2,2,2,"Battlecry: Give a random friendly minion +1 Attack.","Glaivezooka","Common"],
         ["Paladin",3,2,3,"Battlecry: Give a random friendly minion Divine Shield and Taunt.","Coghammer","Epic"],
         ["Rogue",3,1,3,"Has +2 Attack while you have a Mech.","Cogmaster's Wrench","Epic"],
         ["Shaman",3,3,2,"Deathrattle: Give a random friendly Mech +2/+2.","Powermace","Rare"],
         ["Warrior",3,4,2,"50% chance to attack the wrong enemy.","Ogre Warmaul","Common"]
    ]
  return Cards
