#Classic Set

def All():
  Cards=Minions()
  Cards+=Spells()
  Cards+=Weapons()
  return Cards

def Minions():
  #[class,mana cost,attack,health,text,tribe,name,rarity]
  Cards=[["Neutral",0,1,1,"","","Wisp","Common"],
         ["Neutral",1,2,1,"At the end of yout turn, give another random friendly minion +1 Health.","","Young Priestess","Rare"],
         ["Neutral",1,1,1,"Windfury","Beast","Young Dragonhawk","Common"],
         ["Neutral",1,2,1,"Stealth","","Worgen Infiltrator","Common"],
         ["Neutral",1,2,1,"Has Charge while you have a weapon equipped.","Pirate","Southsea Deckhand","Common"],
         ["Neutral",1,0,4,"Taunt","","Shieldbearer","Common"],
         ["Neutral",1,1,2,"Whenever a Secret is played, gain +1/+1.","","Secretkeeper","Rare"],
         ["Neutral",1,1,2,"Whenever a Murloc is summoned, gain +1 Attack.","Murloc","Murloc Tidecaller","Rare"],
         ["Neutral",1,1,2,"Whenever a character us healed, gain +2 Attack.","","Lightwarden","Rare"],
         ["Neutral",1,1,1,"Deathrattle: Deal 2 damage to the enemy hero.","","Leper Gnome","Common"],
         ["Neutral",1,1,2,"Battlecry: Destroy a Murloc and gain +2/+2.","Beast","Hungry Crab","Epic"],
         ["Neutral",1,1,2,"Battlecry: Remove 1 Durability from your opponent's weapon.","Pirate","Bloodsail Corsair","Rare"],
         ["Neutral",1,1,1,"Divine Shield","","Argent Squire","Common"],
         ["Neutral",1,1,1,"Enrage: +5 Attack.","Beast","Angry Chicken","Rare"],
         ["Neutral",1,1,1,"Battlecry: Give a minion +2 Attack this turn.","","Abusive Sergeant","Common"],
         ["Neutral",2,3,2,"Battlecry return a friendly minion from the battlefield to your hand.","","Youthful Brewmaster","Common"],
         ["Neutral",2,3,2,"After you cast a spell, deal 1 damage to ALL minions.","","Wild Pyromancer","Rare"],
         ["Neutral",2,2,3,"Battlecry: Give adjacent minions Taunt.","","Sunfury Protector","Rare"],
         ["Neutral",2,2,2,"The first minion you play each turn costs (1) less.","","Pint-Sized Summoner","Rare"],
         ["Neutral",2,0,4,"At the end of your turn, you have a 50% chance to draw an extra card.","","Nat Pagle","Legendary"],
         ["Neutral",2,4,4,"Battlecry: Enemy spells cost (0) next turn.","","Millhouse Manastorm","Legendary"],
         ["Neutral",2,1,3,"At the end of your turn, give another random minion +1 Attack.","","Master Swordsmith","Rare"],
         ["Neutral",2,2,2,"ALL minions cost (1) more.","","Mana Wraith","Rare"],
         ["Neutral",2,1,3,"Whenever you cast a spell, gain +2 Attack this turn.","","Mana Addict","Rare"],
         ["Neutral",2,3,2,"Battlecry: Deal 3 damage randomly split between all other characters.","","Mad Bomber","Common"],
         ["Neutral",2,0,4,"Whenever a player casts a spell, put a copy into the other player's hand.","","Lorewalker Cho","Legendary"],
         ["Neutral",2,2,1,"Deathrattle: Draw a Card.","","Loot Hoarder","Common"],
         ["Neutral",2,2,2,"After you summon a minion, deal 1 damage to a random enemy.","","Knife Juggler","Rare"],
         ["Neutral",2,3,2,"Can't be targeted by spells or Hero Powers.","Dragon","Faerie Dragon","Common"],
         ["Neutral",2,0,7,"At the start of your turn, destroy ALL minions.","","Doomsayer","Epic"],
         ["Neutral",2,2,2,"Adjacent minions have +1 Attack.","Beast","Dire Wolf Alpha","Common"],
         ["Neutral",2,2,2,"Battlecry: Swap the Attack and Health of a minion.","","Crazed Alchemist","Rare"],
         ["Neutral",2,2,3,"Battlecry: Gain Attack equal to the Attack of your weapon.","Pirate","Bloodsail Raider","Common"],
         ["Neutral",2,1,1,"Spell Damage +1. Deathrattle: Draw a card.","","Bloodmage Thalnos","Legendary"],
         ["Neutral",2,4,5,"Can't attack.","","Ancient Watcher","Rare"],
         ["Neutral",2,2,3,"Enrage: +3 Attack","","Amani Berserker","Common"],
         ["Neutral",3,3,3,"Battlecry: Transform another random minion into a 5/5 Devilsaur or a 1/1 Squirrel.","","Tinkmaster Overspark","Legendary"],
         ["Neutral",3,2,3,"Windfury","","Thrallmar Farseer","Common"],
         ["Neutral",3,2,3,"Taunt. Enrage: +3 Attack","","Tauren Warrior","Common"],
         ["Neutral",3,3,3,"Your other Pirates have +1/+1.","Pirate","Southsea Captain","Epic"],
         ["Neutral",3,3,2,"Divine Shield","","Scarlet Crusader","Common"],
         ["Neutral",3,3,3,"Enrage: Windfury and +1 Attack","","Raging Worgen","Common"],
         ["Neutral",3,2,2,"Whenever you play a card, gain +1/+1.","","Questing Adventurer","Rare"],
         ["Neutral",3,3,3,"ALL other Murlocs have +2/+1.","Murloc","Murloc Warleader","Epic"],
         ["Neutral",3,3,3,"Battlecry: If your opponent has 4 or more minions, take control of one at random.","","Mind Control Tech","Rare"],
         ["Neutral",3,5,5,"Battlecry: Give you opponent 2 Bananas.","Beast","King Mukla","Legendary"],
         ["Neutral",3,4,2,"Stealth","Beast","Jungle Panther","Common"],
         ["Neutral",3,2,1,"Battlecry: Silence a minion.","Beast","Ironbeak Owl","Common"],
         ["Neutral",3,4,7,"Battlecry: Deal 4 damage to HIMSELF.","","Injured  Blademaster","Rare"],
         ["Neutral",3,1,5,"At the end of your turn, deal 1 damage to this minion and summon a 1/1 Imp.","","Imp Master","Rare"],
         ["Neutral",3,2,3,"Deathrattle: Summon a 2/1 Damaged Golem.","Mech","Harvest Golem","Common"],
         ["Neutral",3,2,3,"Whenever a minion dies gain +1 Attack.","","Flesheating Ghoul","Common"],
         ["Neutral",3,2,3,"Destory any minion damaged by this minion.","Beast","Empoeror Cobra","Rare"],
         ["Neutral",3,3,3,"Battlecry: Restore 3 Health.","","Earthen Ring Faseer","Common"],
         ["Neutral",3,1,4,"At the start of your turn, deal 2 damage to a random enemy.","Mech","Demolisher","Rare"],
         ["Neutral",3,2,3,"Battlecry: Give ALL other Murlocs +2 Health.","Murloc","Coldlight Seer","Rare"],
         ["Neutral",3,2,2,"Battlecry Each player draws 2 cards.","Murloc","Coldlight Oracle","Rare"],
         ["Neutral",3,3,3,"Battlecry: All minions lose Divine Shield. Gain +3/+3 for each Shield lost.","","Blood Knight","Epic"],
         ["Neutral",3,4,4,"Battlecry: Give your opponent a Mana Crystal.","","Arcane Golem","Rare"],
         ["Neutral",3,0,3,"At the start of your turn, swap this minion with a random one in your hand.","Mech","Alarm-o-Bot","Rare"],
         ["Neutral",3,1,3,"Whenever this minion takes damage, draw a card.","","Acolyte of Pain","Common"],
         ["Neutral",4,3,5,"Whenever you cast a spell summon a 1/1 Violet Apperentice.","","Violet Teacher","Rare"],
         ["Neutral",4,4,1,"Battlecry: Gain +1 Health for each card in your hand.","Dragon","Twilight Drake","Rare"],
         ["Neutral",4,4,3,"Battlecry: Silence a minion.","","Spellbreaker","Common"],
         ["Neutral",4,3,3,"Divine Shield","","Silvermoon Guardian","Common"],
         ["Neutral",4,1,7,"Taunt","","Mogu'shan Warden","Common"],
         ["Neutral",4,3,3,"Taunt. Costs (1) less per Attack of your weapon.","Pirate","Dread Corsair","Common"],
         ["Neutral",4,2,3,"Battlecry: Give adjacent minions +1/+1 and Taunt.","","Defender of Argus","Rare"],
         ["Neutral",4,4,4,"Battlecry: Give a minion +2 Attack this turn.","","Dark Iron Dwarf","Common"],
         ["Neutral",4,4,2,"Whenever one of your other minions dies, draw a card.","","Cult Master","Common"],
         ["Neutral",4,2,5,"Battlecry: Give adjacent minions Spell Damage +1.","","Ancient Mage","Rare"],
         ["Neutral",4,5,4,"Battlecry: Return a friendly minion from the battlefield to your hand.","","Ancient Brewmaster","Common"],
         ["Neutral",5,7,6,"Your minions cost (3) more.","","Venture Co. Mercenary","Common"],
         ["Neutral",5,5,5,"Stealth","Beast","Stranglethorn Tiger","Common"],
         ["Neutral",5,3,5,"Battlecry: Destroy a random enemy minion with 2 or less Attack.","Beast","Stampeding Kodo","Rare"],
         ["Neutral",5,4,6,"Enrage: Your weapon has +2 Attack.","","Spiteful Smith","Rare"],
         ["Neutral",5,4,4,"Battlecry: Summon a 2/2 Squire.","","Silver Hand Knight","Common"],
         ["Neutral",5,6,2,"Charge. Battlecry: Summon two 1/1 Whelps for your oppenent.","","Leeroy Jenkins","Legendary"],
         ["Neutral",5,5,4,"Battlecry: Destroy your opponent's weapon and draw cards equal to its Durability.","","Harrison Jones","Legendary"],
         ["Neutral",5,3,6,"Taunt","","Fen Creeper","Common"],
         ["Neutral",5,3,3,"Battlecry: Choose a minion and become a copy of it.","","Facelss Manipulator","Epic"],
         ["Neutral",5,5,4,"Battlecry: Give your weapon +1/+1.","Pirate","Captain Greenskin","Legendary"],
         ["Neutral",5,4,2,"Battlecry: Destroy a minion with an Attack of 7 or more.","","Big Game Hunter","Epic"],
         ["Neutral",5,4,4,"Spell Damage +1. Battlecry: Draw a card.","Dragon","Azure Drake","Rare"],
         ["Neutral",5,4,4,"Taunt. Deathrattle: Deal 2 damage to ALL characters.","","Abomination","Rare"],
         ["Neutral",6,4,5,"Windfury","","Windfury Harpy","Common"],
         ["Neutral",6,4,5,"Battlecry: Destroy an enemy minion with Taunt.","","The Black Knight","Legendary"],
         ["Neutral",6,9,7,"Deathrattle: Summon a 3/3 Finkle Einhorn for your opponent.","Beast","The Beast","Legendary"],
         ["Neutral",6,5,5,"Deathrattle: Take control of a random enemy minion.","","Sylvanas Windrunner","Legendary"],
         ["Neutral",6,4,5,"Taunt. Divine Shield","","Sunwalker","Rare"],
         ["Neutral",6,5,4,"Battelcry: Restor 4 Health to your hero.","","Priestess of Elune","Common"],
         ["Neutral",6,7,5,"Whenever you play a card summon a 2/1 Flame of Azzinoth.","Demon","Illidan Stormrage","Legendary"],
         ["Neutral",6,4,4,"At the end of your turn, summon a 2/2 Gnoll with Taunt.","","Hogger","Legendary"],
         ["Neutral",6,4,4,"Whenever you cast a spell draw a card.","","Gadgetzan Auctioneer","Rare"],
         ["Neutral",6,5,5,"Battlecry: Freeze a character.","","Frost Elemental","Common"],
         ["Neutral",6,4,5,"Deathrattle: Summon a 4/5 Bain Bloodhoof.","","Cairne Bloodhoof","Legendary"],
         ["Neutral",6,4,2,"Charge Divine Shield","","Argent Commander","","Rare"],
         ["Neutral",7,7,5,"Stealth","","Ravenholdt Assassin","Rare"],
         ["Neutral",7,7,5,"At the end of your turn, deal 2 damage to ALL other characters.","","Baron Geddon","Legendary"],
         ["Neutral",8,8,8,"Can't attack. At the end of your turn, deal 8 damage to a random enemy.","","Ragnaros the Firelord","Legendary"],
         ["Neutral",8,7,7,"At the end of each turn, gain +1/+1.","","Gruul","Legendary"],
         ["Neutral",9,4,12,"At the end of your turn, add a Dream Card to your hand.","Dragon","Ysera","Legendary"],
         ["Neutral",9,8,8,"Battlecry: Summon 1/1 Whelps until yout side of the battlefield is full.","Dragon","Onyxia"],
         ["Neutral",9,8,8,"Players only have 15 seconds to take their turns.","Dragon","Nozdormu","Legendary"],
         ["Neutral",9,4,12,"Spell Damage +5","Dragon","Malygos","Legendary"],
         ["Neutral",9,8,8,"Battlecry: Set a hero's remaining Health to 15.","Dragon","Alexstrasza","Legendary"],
         ["Neutral",10,8,8,"Costs (1) less for each other minion on the battlefield.","","Sea Giant","Epic"],
         ["Neutral",10,12,12,"Battlecry: Destroy all other minions and discard your hand.","Dragon","Deathwing","Legendary"],
         ["Neutral",12,8,8,"Costs (1) less for each other card in your hand.","","Mountain Giant","Epic"],
         ["Neutral",25,8,8,"Costs (1) less for each damage your hero has taken.","","Molten Giant","Epic"],
         ["Druid",4,2,2,"Choose One - Deal 2 damage; or Silence a minion.","","Keeper of the Grove","Rare"],
         ["Druid",5,4,4,"Choose One - Charge; or +2 Health and Taunt.","","Druid of the Claw","Common"],
         ["Druid",7,5,5,"Choose One - +5 Attack; or +5 Health and Taunt.","","Ancient of War","Epic"],
         ["Druid",7,5,5,"Choose One - Draw a card; or Restore 5 Health","","Ancient of Lore","Epic"],
         ["Druid",9,5,8,"Choose One - Give yout other minions +2/+2; or Summon two 2/2 Treants with Taunt.","","Cenarius","Legendary"],
         ["Hunter",2,2,2,"Whenever a friendly Beast dies, gain +2/+1.","Beast","Scavenging Hyena","Common"],
         ["Hunter",6,6,5,"Deathrattle: Summon two 2/2 Hyenas.","Beast","Savannah Highmane","Rare"],
         ["Hunter",9,8,8,"Charge","Beast","King Krush","Legendary"],
         ["Mage",1,1,3,"Whenever you cast a spell gain +1 Attack.","","Mana Wyrm","Common"],
         ["Mage",2,3,2,"Your spells cost (1) less.","","Sorcerer's Apprentice","Common"],
         ["Mage",3,4,3,"Battlecry: The next Secret you play this turn costs (0).","","Kirin Tor Mage","Rare"],
         ["Mage",4,3,3,"If you control a Secret at the end of your turn, gain +2/+2.","","Ethereal Arcanist","Rare"],
         ["Mage",7,5,7,"Whenever you cast a spell, add a 'Fireball' spell to your hand.","","Archmage Antonidas","Legendary"],
         ["Paladin",2,2,2,"Battlecry: Give a friendly minion Divine Shield.","","Argent Protector","Common"],
         ["Paladin",3,3,3,"Battlecry: Change an enemy minion's Attack to 1.","","Aldor Peacekeeper","Rare"],
         ["Paladin",8,6,6,"Divine Shield. Taunt. Deathrattle: Equip a 5/3 Ashbringer.","","Tirion Fordring","Legendary"],
         ["Priest",2,0,5,"At the start of your turn, restore 3 Health to a damaged friendly character.","","Lightwell","Rare"],
         ["Priest",4,0,5,"This minion's Attack is always equal to its Health.","","Lightspawn","Common"],
         ["Priest",4,3,5,"Your cards and powers that restore Health now deal damage instead.","","Auchenai Soulpriest","Rare"],
         ["Priest",6,6,6,"Battlecry: Give a friendly minion +3 Health.","","Temple Enforcer","Common"],
         ["Priest",6,4,5,"Battlecry: Take control of an enemy minion that has 2 or less Attack.","","Cabal Shadow Priest","Epic"],
         ["Priest",7,7,7,"Double the damage and healing of your spells and Hero Power.","","Prophet Velen","Legendary"],
         ["Rogue",2,1,1,"Stealth. Destroy any minion damaged by this minion.","","Patient Assassin","Epic"],
         ["Rogue",2,2,2,"Combo: Summon a 2/1 Defias Bandit.","","Defias Ringleader","Common"],
         ["Rogue",3,3,3,"Combo: Deal 2 damage.","","SI:7 Agent","Rare"],
         ["Rogue",3,2,2,"Combo: Gain +2/+2 for each card played earlier this turn.","","Edwin VanCleef","Legendary"],
         ["Rogue",4,4,4,"Battlecry: Give a friendly minion Stealth until your next turn.","","Master of Disguise","Rare"],
         ["Rogue",6,5,3,"Combo: Return a minion to its owner's hand.","","Kidnapper","Epic"],
         ["Shaman",1,3,1,"Windfury. Overload: (2)","","Dust Devil","Common"],
         ["Shaman",3,2,4,"Whenever you play a card with Overload, gain +1/+1.","","Unbound Elemental","Common"],
         ["Shaman",3,0,3,"At the end of your turn, draw a card.","Totem","Mana Tide Totem","Rare"],
         ["Shaman",5,7,8,"Taunt. Overload: (3)","","Earth Elemental","Epic"],
         ["Shaman",8,3,5,"Winfury, Charge, Divine Shield, Taunt","","Al'Akir the Windlord","Legendary"],
         ["Warlock",1,3,2,"Battlecry: Deal 3 damage to your hero.","Demon","Flame Imp","Common"],
         ["Warlock",1,0,1,"Stealth. At the end of your turn, give another random friendly minion +1 Health.","Demon","Blood Imp","Common"],
         ["Warlock",3,3,3,"Battlecry: Destroy the minions on either side of this minions and gain their Attack and Health.","Demon","Void Terror","Rare"],
         ["Warlock",3,3,5,"Taunt. Battlecry: Destroy one of your Mana Crystals.","Demon","Felguard","Rare"],
         ["Warlock",4,0,4,"Your minons cost (2) less, but not less than (1).","","Summoning Portal","Common"],
         ["Warlock",4,5,6,"Battlecry: Deal 5 damage to your hero.","Demon","Pit Lord","Epic"],
         ["Warlock",5,5,7,"Charge. Battlecry: Discard two random cards.","Demon","Doomguard","Rare"],
         ["Warlock",9,3,15,"Battlecry: Destroy your hero and replace it with Lord Jaraxxus.","Demon","Lord Jaraxxus","Legendary"],
         ["Warrior",2,2,2,"Battlecry: Deal 1 damage to a minion and give it +2 Attack.","","Cruel Taskmaster","Common"],
         ["Warrior",2,1,4,"Whenever a friendly minion takes damage, gain 1 Armor.","","Armorsmith","Rare"],
         ["Warrior",3,2,4,"Whenever a minion takes damage, gain +1 Attack.","","Frothing Berserker","Rare"],
         ["Warrior",4,3,3,"Battlecry: Equip a 2/2 weapon.","","Arethi Weaponsmith","Common"],
         ["Warrior",9,4,9,"Charge. Enrage: +6 Attack","","Grommash Hellscream","Legendary"]
    ]
  return Cards

def Spells():
  #[class,mana cost,text,name,rarity]
  Cards=[["Druid",1,"Deal damage equal to your hero's Attack to a minion.","Savagery","Rare"],
         ["Druid",1,"Destroy a minion. Your opponent draws 2 cards.","Naturalize","Common"],
         ["Druid",2,"Choose One - Deal 3 damage to a minion; or 1 damage and draw a card.","Wrath","Common"],
         ["Druid",2,"Choose One - Give your minions +1/+1; or Summon a 3/2 Panther.","Power of the Wild","Common"],
         ["Druid",3,"Choose One - Give a minion +4 Attack; or +4 Health and Taunt.","Mark of Nature","Common"],
         ["Druid",4,'Give your minions "Deathrattle: Summon a 2/2 Treant."',"Soul of the Forest","Common"],
         ["Druid",4,"Give your hero +4 Attack this turn and 4 Armor.","Bite","Rare"],
         ["Druid",5,"Choose One - Deal 5 damage to a minion; or 2 damage to all enemy minions.","Starfall","Rare"],
         ["Druid",5,"Choose One - Gain 2 Mana Crystals; or Draw 3 cards.","Nourish","Rare"],
         ["Druid",5,"Summon three 2/2 Treants.","Force of Nature","Epic"],
         ["Hunter",1,"Give a friendly Beast +2 Attack and Immune this turn.","Bestial Wrath","Epic"],
         ["Hunter",2,"Secret: After your opponent plays a minion, deal 4 damage to it.","Snipe","Common"],
         ["Hunter",2,"Secret: When one of your minions is attacked, summon three 1/1 Snakes.","Snake Trap","Epic"],
         ["Hunter",2,"Secret: When a character attacks your hero, instead he attacks another random character.","Misdirection","Rare"],
         ["Hunter",2,"Secret: When an enemy minion attacks, return it to it's owner's hand and it costs (2) more.","Freezing Trap","Common"],
         ["Hunter",2,"All minions lose Stealth. Destroy all enemy Secrets. Draw a card.","Flare","Rare"],
         ["Hunter",2,"For each enemy minion, summon a 1/1 Hound with Charge.","Unleash the Hounds","Common"],
         ["Hunter",3,"Destroy a random enemy minion.","Deadly Shot","Common"],
         ["Hunter",5,"Deal 5 damage to a minion and 2 damage to adjacent ones.","Explosive Shot","Rare"],
         ["Mage",1,"Freeze a character. If it was already Frozen, deal 4 damage instead.","Ice Lance","Common"],
         ["Mage",3,"Secret: When a minion attacks your hero, destroy it.","Vaporize","Rare"],
         ["Mage",3,"Secret: When an enemy casts a spell on a minion, summon a 1/3 as the new target.","Spellbender","Epic"],
         ["Mage",3,"Secret: After your opponent plays a minion, summon a copy of it.","Mirror Entity","Common"],
         ["Mage",3,"Secret: When your hero takes fatal damage, prevent it and become Immune this turn.","Ice Block","Epic"],
         ["Mage",3,"Secret: When your hero is attacked, gain 8 Armor.","Ice Barrier","Common"],
         ["Mage",3,"Secret: When your opponent casts a spell, Counter it.","Counterspell","Rare"],
         ["Mage",4,"Freeze a minion and the minions next to it, and deal 1 damage to them.","Cone of Cold","Common"],
         ["Mage",6,"Deal 2 damage to all enemy minions and Freeze them.","Blizzard","Rare"],
         ["Mage",10,"Deal 10 damage.","Pyroblast","Epic"],
         ["Paladin",1,"Secret: After your opponent plays a minion, reduce its Health to 1.","Repentance","Common"],
         ["Paladin",1,"Secret: When one of your minions dies, return it to life with 1 Health.","Redemption","Common"],
         ["Paladin",1,"Secret: When an enemy attacks, summon a 2/1 Defender as the new target.","Noble Sacrifice","Common"],
         ["Paladin",1,"Secret: When our hero takes damage, deal that much damage to the enemy hero.","Eye for an Eye","Common"],
         ["Paladin",1,"Choose a minion. Whenever it attacks, draw a card.","Blessing of Wisdom","Common"],
         ["Paladin",2,"Change the Health of ALL minions to 1.","Equality","Rare"],
         ["Paladin",3,"Draw cards until you have as many in hand as your opponent.","Divine Favor","Rare"],
         ["Paladin",5,"Draw a card and deal damage equal to its cost.","Holy Wrath","Rare"],
         ["Paladin",5,"Double a minion's Attack.","Blessed Champion","Rare"],
         ["Paladin",6,"Deal 8 damage randomly split among all enemies.","Avenging Wrath","Epic"],
         ["Paladin",8,"Restore 8 Health. Draw 3 cards.","Lay on Hands","Epic"],
         ["Priest",0,"Silence a minion.","Silence","Common"],
         ["Priest",0,"Restore 4 Health to ALL minions.","Circle of Healing","Common"],
         ["Priest",1,"Change a minion's Attack to be equal to its Health.","Inner Fire","Common"],
         ["Priest",3,"Copy 2 cards from your opponent's deck and put them into your hand.","Thoughtsteal","Common"],
         ["Priest",3,"Your hero Power becomes 'Deal 2 damage'. If already in Shadowform: 3 damage.","Shadowform","Epic"],
         ["Priest",4,"Gain control of an enemy minion with 3 or less Attack until end of turn.","Shadow Madness","Rare"],
         ["Priest",4,"Put a copy of a random minion from your opponent's deck into the battlefield.","Mindgames","Epic"],
         ["Priest",4,"Silence all enemy minions. Draw a card.","Mass Dispel","Rare"],
         ["Priest",6,"Deal 5 damage. Restore 5 Health to your Hero.","Holy Fire","Rare"],
         ["Rogue",0,"Return a friendly minion to your hand. It costs (2) less.","Shadowstep","Common"],
         ["Rogue",0,"The next spell you cast this turn costs (3) less","Preparation","Epic"],
         ["Rogue",1,"Give your minions Stealth until your next turn.","Conceal","Common"],
         ["Rogue",1,"Give a minion +2 Attack. Combo: +4 attack instead.","Cold Blood","Common"],
         ["Rogue",2,"Deal 2 damage. Combo: Deal 4 damage instead.","Eviscerate","Common"],
         ["Rogue",2,"Force an enemy minion to deal it damage to the minions next to it.","Betrayal","Common"],
         ["Rogue",3,"Deal 2 damage to the enemy hero. Combo: Return this to your hand next turn.","Headcrack","Rare"],
         ["Rogue",4,"Destroy your weapon and deal its damage to all enemy minions.","Blade Flurry","Rare"],
         ["Shaman",1,"Deal 3 damage. Overload: (1)","Lightning Bolt","Common"],
         ["Shaman",1,"Deal 2 damage to 2 random enemy minions. Overload: (2)","Forked Lighting","Common"],
         ["Shaman",1,"Silence a minion, then deal 1 damage to it.","Earth Shock","Common"],
         ["Shaman",2,'Give a minion "Deathrattle: Resummon this minion."',"Ancestral Spirit","Rare"],
         ["Shaman",3,"Deal 2-3 damage to all enemy minions. Overload: (2)","Lightning Storm","Rare"],
         ["Shaman",3,"Deal 5 damage. Overload: (2)","Lava Burst","Rare"],
         ["Shaman",3,"Summon two 2/3 Spirit Wolves with Taunt. Overload:(2)","Feral Spirit","Rare"],
         ["Shaman",3,"Draw a card. That card costs (3) less.","Far Sight","Epic"],
         ["Warlock",1,"Give a friendly minion +4/+4 until end of turn. Then, it dies. Horribly.","Power Overwhelming","Common"],
         ["Warlock",2,"Deal 2 damage to a minion. If it's a friednly Demon, give it +2/+2 instead.","Demonfire","Common"],
         ["Warlock",3,"Put 2 random Demons from your deck into your hand.","Sense Demons","Common"],
         ["Warlock",4,"Destroy a friednly minion and deal it's Attack damage to all enemy minions.","Shadowflame","Rare"],
         ["Warlock",5,"Deal 2 damage to a character. If that kills it, summon a random Demon","Bane of Doom","Epic"],
         ["Warlock",6,"Destroy a minion. Restore 3 Health to your hero.","Siphon Soul","Rare"],
         ["Warlock",8,"Destroy all minions.","Twisting Nether","Epic"],
         ["Warrior",0,"Deal 1 damage to a minion and give it +2 Attack.","Inner Rage","Common"],
         ["Warrior",1,"If you have a wepaon, give it +1/+1. Otherwise equip a 1/3 weapon.","Upgrade!","Rare"],
         ["Warrior",1,"Deal 1 damage to a minion for each Armor you have.","Shield Slam","Epic"],
         ["Warrior",2,"Deal 2 dmage to a minion. If it survives, draw a card.","Slam","Common"],
         ["Warrior",2,"Give a damaged minion +3/+3.","Rampage","Common"],
         ["Warrior",2,"Your minions can't be reduced below 1 Health this turn. Draw a card.","Commanding Shout","Rare"],
         ["Warrior",2,"Draw a card for each damaged friendly character.","Battle Rage","Common"],
         ["Warrior",4,"Deal 4 damage. If you have 12 or less Health, deal 6 damage instead.","Mortal Strike","Rare"],
         ["Warrior",5,"Destroy all minions except one. (chosen randomly)","Brawl","Epic"]
    ]

  return Cards

def Weapons():
  #[class,mana cost,attack,durability,text,name,rarity]
  Cards=[["Hunter",3,3,2,"Whenever a friendly Secret is revealed, gain +1 Durability","Eaglehorn Bow","Rare"],
         ["Hunter",7,5,2,"Your hero is Immune while attacking.","Gladiator's Longbow","Epic"],
         ["Paladin",3,1,5,"After you summon a minion, give it +1/+1 and this loses 1 Durability.","Sword or Justice","Epic"],
         ["Rogue",3,2,2,"Battlecry: Deal 1 damage. Combo: Deal 2 instead.","Perdition's Blade","Rare"],
         ["Shaman",2,2,3,"Overload:(1)","Stormforged Axe","Common"],
         ["Shaman",5,2,8,"Windfury, Overload:(2)","Doomhammer","Epic"],
         ["Warrior",7,7,1,"Attacking a minion costs 1 Attack instead of 1 Durability.","Gorehowl","Epic"]
    ]
  return Cards
