#Whispers of the Old Gods Set

def All():
  Cards=Minions()
  Cards+=Spells()
  Cards+=Weapons()
  return Cards

def Minions():
  #[class,mana cost,attack,health,text,tribe,name,rarity]
  Cards=[["Neutral",1,1,1,"Deathrattle: Give a random friednly minion +1/+1.","","Zealous Initiate","Common"],
         ["Neutral",1,1,1,"Deathrattle: Deal 1 damage to all minions.","","Tentacle of N'Zoth","Common"],
         ["Neutral",1,1,1,"Each turn this is in your hand, transform it into a random minion.","","Shifter Zerus","Legendary"],
         ["Neutral",2,3,1,"Stealth","","Twisted Worgen","Common"],
         ["Neutral",2,1,4,"Taunt. Battlecry: Give your C'thun Taunt (Wherever it is).","","Twilight Geomancer","Common"],
         ["Neutral",2,2,4,"At the start of your opponent's turn, they have a 50% chance to draw an extra card.","","Nat, the Darkfisher","Legendary"],
         ["Neutral",2,4,1,"","Beast","Duskboar","Common"],
         ["Neutral",2,2,1,"Battlecry: Summon a 1/1 Ooze with Taunt.","Murloc","Bilefin Tidehunter","Common"],
         ["Neutral",2,2,3,"Battlecry: Give your C'Thun +2/+2 (wherever it is).","","Beckoner of Evil","Common"],
         ["Neutral",3,3,4,"At the end of your turn, give your C'Thun +1/+1 (wherever it is).","","Twilight Elder","Common"],
         ["Neutral",3,2,4,"Taunt","","Squirming Tentacle","Common"],
         ["Neutral",3,2,2,"Deathrattle: Give your minions +1/+1.","","Spawn of N'Zoth","Common"],
         ["Neutral",3,3,5,"Can only attack if your hero attacked this turn.","","Silithid Swarmer","Rare"],
         ["Neutral",3,2,1,"Battlecry: Deal 2 damage. Give your C'Thun +2/+2 (wherever it is).","","Disciple of C'Thun","Rare"],
         ["Neutral",3,1,5,"","","Am'gam Rager","Common"],
         ["Neutral",4,1,1,"Deathrattle: Summon a 5/5 Faceless Destroyer.","","Twilight Summoner","Epic"],
         ["Neutral",4,4,2,"Deathrattle: Draw a card.","","Polluted Hoarder","Common"],
         ["Neutral",4,1,4,"Battlecry: Gain +1 Attack for each other card in your hand.","Dragon","Midnight Drake","Rare"],
         ["Neutral",4,2,3,"Taunt. Deathrattle: Summon a 2/2 Slime.","","Infested Tauren","Common"],
         ["Neutral",4,1,1,"Taunt. Battlecry: Copy a firendly minion's Attack and Health.","","Faceless Shambler","Epic"],
         ["Neutral",4,2,2,"Spell Damage +2","","Evolved Kobold","Common"],
         ["Neutral",4,2,4,"Battlecry: Destroy all enemy Secrets. Gain +1/+1 for each.","","Eater of Secrets","Rare"],
         ["Neutral",4,3,3,"Taunt. Battlecry: Gain +1 Health for each enemy minion.","","Cyclopian Horror","Epic"],
         ["Neutral",4,4,2,"Divine Shield. Battlecry: Give your C'Thun +2/+2 (wherever it is).","","C'Thun's Chosen","Common"],
         ["Neutral",4,2,5,"Your weapons cost (2) less.","Pirate","Blackwater Pirate","Rare"],
         ["Neutral",4,3,5,"Enrage: +2 Attack.","","Aberrant Berserker","Common"],
         ["Neutral",5,0,7,"At the start of your turn, set this minion's Attack to 7.","","Validated Doomsayer","Epic"],
         ["Neutral",5,3,4,"Taunt. Divine Shield.","Mech","Psych-o-Tron","Common"],
         ["Neutral",5,3,6,"Battlecry: Swap stats with a friendly minion.","","Darkspeaker","Epic"],
         ["Neutral",5,4,4,"Battlecry: For each enemy minion, restore 2 Health to you hero.","","Cult Apothecary","Common"],
         ["Neutral",5,3,6,"Taunt. Whenever this minion takes damage, give your C'Thun +1/+1 (wherever it is).","","Crazed Worshipper","Epic"],
         ["Neutral",5,6,6,"Deathrattle: Restore 8 Health to the enemy hero.","Mech","Corrupted Healbot","Rare"],
         ["Neutral",6,7,6,"Battlecry: Give your C'Thun +2/+2 (wherever it is).","","Skeram Cultist","Rare"],
         ["Neutral",6,2,8,"At the start of your turn, double this minion's Attack.","Dragon","Scaled Nightmare","Epic"],
         ["Neutral",6,4,4,"At the start of your turn, reduce this card's Cost by (1).","","Nerubian Prophet","Common"],
         ["Neutral",6,5,5,"Battlecry: Add 2 Bananas to your hand.","Beast","Mukla, Tyrant of the Vale","Legendary"],
         ["Neutral",6,2,3,"Battlecry: Deal 2 damage to all non-Murloc minions.","Murloc","Corrupted Seer","Rare"],
         ["Neutral",6,4,6,"At the start of your turn, put a 10-Cist minion from your deck into your hand.","","Ancient Harbinger","Epic"],
         ["Neutral",7,4,6,"Taunt. Battlecry: If your C'Thun has at least 10 Attack, summon another Emperor.","","Twin Emperor Vel'lor","Legendary"],
         ["Neutral",7,6,6,"Whenever this minion takes damage, summon a 2/2 Gnoll with Taunt.","","Hogger, Doom of Elwynn","Legendary"],
         ["Neutral",7,5,5,"Windfury","Beast","Grotesque Dragonhawk","Common"],
         ["Neutral",7,6,8,"Taunt","","Bog Creeper","Common"],
         ["Neutral",8,6,7,"Whenever this attacks and kills a minion, gain +2/+2.","","The Boogeymonster","Legendary"],
         ["Neutral",8,6,10,"","","Eldritch Horror","Common"],
         ["Neutral",8,7,9,"Battlecry: Give your C'Thun +2/+2 (wherever it is). If it's dead, suffle it into your deck.","","Doomcaller","Rare"],
         ["Neutral",9,5,9,"Taunt. Can't be targeted by spells or Hero Powers.","","Soggoth the Slitherer","Legendary"],
         ["Neutral",9,9,9,"If you control two of these at the end of your turn, merge them into 'The Ancient One'.","","Blood of The Ancient One","Epic"],
         ["Neutral",10,10,10,"At the end of yout turn, put a minion from your deck into the battlefield.","","Y'Saarj, Rage Unbound","Legendary"],
         ["Neutral",10,7,5,"Battlecry: Cast a random spell for each spell you've cast this game (targets chsoen randomly).","","Yogg-Saron, Hope's End","Legendary"],
         ["Neutral",10,5,7,"Battlecry: Summon your Deathrattle minions that died this game.","","N'Zoth, the Corruptor","Legendary"],
         ["Neutral",10,10,10,"","","Faceless Behemoth","Common"],
         ["Neutral",10,12,12,"Deathrattle: Put all Dragons from your hand into the battlefield.","Dragon","Deathwing, Dragonlord","Legendary"],
         ["Neutral",10,6,6,"Battlecry: Deal damage equal to this minion's Attack randomlysplit among all enemies.","","C'Thun","Legendary"],
         ["Druid",1,1,1,"Battlecry: Spend all your Mana, Gain +1/+1 for each mana spent.","","Forbidden Ancient","Epic"],
         ["Druid",3,2,2,"After your summon a minion, give it +1/+1.","","Addled Grizzly","Rare"],
         ["Druid",4,3,3,"Coose One- Summon a 2/2 Slime; or Gain an empty Mana Crystal.","","Mire Keeper","Rare"],
         ["Druid",4,4,5,"Battlecry: If your C'Thun has at least 10 Attack, gain +5 Health.","","Klaxxi Amber-Weaver","Rare"],
         ["Druid",4,3,5,"Your Choose One cards have both effects combined.","","Fandral Staghelm","Legendary"],
         ["Druid",6,5,7,"Taunt. Battlecry: Give your C'Thun +3/+3 (wherever it is).","","Dark Arakkoa","Common"],
         ["Hunter",1,2,1,"Deathrattle: Deal 1 damage to a random enemy.","Beast","Fiery Bat","Common"],
         ["Hunter",3,4,2,"Battlecry: Give all Deathrattle minions in your hand +1/+1.","","Forlorn Stalker","Rare"],
         ["Hunter",3,2,5,"","Beast","Carrion Grub","Common"],
         ["Hunter",4,3,3,"Deathrattle: Summon two 1/1 Spiders.","Beast","Infested Wolf","Rare"],
         ["Hunter",5,6,5,"Battlecry: Tigger a friendly minion's Deathrattle effect.","Beast","Princess Huhuran","Legendary"],
         ["Hunter",8,8,8,"Whenever this attacks and kills a minion, it may attack again.","Beast","Giant Sand Worm","Epic"],
         ["Mage",2,3,2,"Spell Damage +1. After you cast a spell, give your C'Thun +1/+1 (wherever it is).","","Cult Sorcerer","Rare"],
         ["Mage",3,2,2,"Battlecry: Deal 1 damage to all enemy minions.","","Twilight Flamecaller","Common"],
         ["Mage",4,2,4,"After you cast a spell, Freeze a random enemy.","","Demented Frostcaller","Rare"],
         ["Mage",5,5,4,"Battlecry: Cast a random spell that costs (5) or less (targets chosen randomly).","","Servant of Yogg-Saron","Legendary"],
         ["Mage",6,5,5,"Battlecry: Summon a random 3-Cost minion.","","Faceless Summoner","Common"],
         ["Mage",8,8,6,"Deathrattle: Deal 8 damage to all minions.","","Anomalus","Legendary"],
         ["Paladin",1,1,3,"Battlecry: Your Hero Power becomes 'Summon a 1/1 Murloc.'","Murloc","Vilefin Inquisitor","Epic"],
         ["Paladin",1,2,1,"Deathrattle: Give a random friendly minion Divine Shield.","","Selfless Hero","Rare"],
         ["Paladin",3,3,3,"Whenever you summon a 1-Health minion, give it Divine Shield.","","Steward of Darkshire","Rare"],
         ["Paladin",8,8,8,"At the end of your turn, restore 8 Health to a damaged friendly character.","","Ragnaros, Lightlord","Legendary"],
         ["Priest",4,4,3,"Deathrattle: Copy a card from your opponent's deck and add it to your hand.","","Shifting Shade","Rare"],
         ["Priest",4,3,6,"Whenever a character is healed, give your C'Thun +1/+1 (wherever it is).","","Hooded Acolyte","Common"],
         ["Priest",5,6,5,"Battlecry: If your C'Thun has at least 10 Attack, restore 10 Health to your hero.","","Twilight Darkmender","Rare"],
         ["Priest",5,4,5,"Battlecry: Restore 5 Health.","","Darkshire Alchemist","Common"],
         ["Priest",6,5,5,"Battlecry: Summon a 1/1 copy of each of your other minions.","","Herald Volazj","Legendary"],
         ["Rogue",1,1,2,"Combo: gain +1/+1.","","Bladed Cultist","Common"],
         ["Rogue",2,2,2,"Deathrattle: Add a random class card to your hand (from your opponent's class).","","Undercity Huckster","Rare"],
         ["Rogue",4,3,2,"Battlecry and Deathrattle: Add a random Toxin card to you hand.","","Xaril, Poisoned Mind","Legendary"],
         ["Rogue",4,4,4,"Deathrattle: Give your weapon +2 Attack.","Pirate","Southsea Squidface","Common"],
         ["Rogue",5,4,4,"Battlecry: Choose a friendly minion. Add a 1/1 copy to your hand that costs (1).","","Shadowcaster","Epic"],
         ["Rogue",9,4,4,"Battlecry: Destroy a minion. Add its Attack and Health to your C'Thun's (wherever it is).","","Blade of C'Thun","Epic"],
         ["Shaman",2,3,2,"Battlecry: Unlock your Overloaded Mana Crystals.","","Eternal Sentinel","Epic"],
         ["Shaman",4,4,5,"Battlecry: Transform a friendly minion into a random into a random one that costs (1) more.","","Master of Evolution","Rare"],
         ["Shaman",4,7,7,"Overload: (2)","","Flamewreathed Faceless","Common"],
         ["Shaman",5,4,6,"Whenever your spells deal damage, restore that much Health to your hero.","","Hallazeal the Ascended","Legendary"],
         ["Shaman",6,5,5,"Taunt. Costs (1) less for each Totem you've summoned this game.","","Thing from Below","Rare"],
         ["Warlock",1,1,1,"Deathrattle: Summon a 1/1 Shadowbeast.","","Possessed Villager","Common"],
         ["Warlock",2,3,2,"Battlecry: Discard a random card. Deathrattle: Draw a card.","","Darkshire Librarian","Rare"],
         ["Warlock",3,1,5,"After you summon a minion, gain +1 Attack.","","Darkshire Councilman","Common"],
         ["Warlock",5,5,6,"Whenever a friendly minion dies, give your C'Thun +1/+1 (wherever it is).","","Usher of Souls","Common"],
         ["Warlock",7,7,7,"Battlecry: The next spell you cast this turn costs Health instead of Mana.","","Cho'gall","Legendary"],
         ["Warrior",1,1,1,"Battlecry: Equip a 1/3 Rusty Hook.","Pirate","N'Zoth's First Mate","Common"],
         ["Warrior",3,3,3,"Battlecry: Deal 1 damage to all other minions.","","Ravaging Ghoul","Common"],
         ["Warrior",3,3,4,"Battlecry: If you control another Pirate, give your weapon +1/+1.","Pirate","Bloodsail Cultist","Rare"],
         ["Warrior",4,2,6,"Taunt. Enrage: +3 Attack.","","Bloodhoof Brave","Common"],
         ["Warrior",7,6,5,"Battlecry: Equip a random weapon.","","Malkorok","Legendary"],
         ["Warrior",7,6,6,"Battlecry: If your C'Thun has atleast 10 Attack, gain 10 Armor.","","Ancient Shieldbearer","Rare"]
    ]
  return Cards

def Spells():
  #[class,mana cost,text,name,rarity]
  Cards=[["Druid",2,"Give a minion +2/+2. If it's a Beast, draw a card.","Mark of Y'Shaarj","Common"],
         ["Druid",3,"Choose One- Give your hero +4 Attack this turn; or Gain 8 Armor.","Common"],
         ["Druid",7,"Choose One- Summon seven 1/1 Wisps; or Give your minions +2/+2.","Wisps of the Old Gods","Epic"],
         ["Hunter",1,"Deal 1 damage. Summon a 1/1 Mastiff.","On the Hunt","Common"],
         ["Hunter",3,'Give your minions "Deathrattle: Add a random Beast to your hand."',"Infest","Rare"],
         ["Hunter",9,"Summon all three Animal Companions.","Call of the Wild","Epic"],
         ["Mage",0,"Spend all your Mana. Deal that much damage to a minion.","Forbidden Flame","Epic"],
         ["Mage",2,"Destroy a Frozen minion.","Shatter","Common"],
         ["Mage",5,"Add 3 random Mage spells to your hand.","Cabalist's Tome","Epic"],
         ["Paladin",0,"Spend all your Mana. Restore twice that much Health.","Forbidden Healing","Epic"],
         ["Paladin",1,"Give a minion +1/+2.","Divine Strength","Common"],
         ["Paladin",2,"Discover a minion. Give it +1/+1.","A Light in the Darkness","Common"],
         ["Paladin",5,"Summon five 1/1 Silver Hand Recruits.","Stand Against Darkness","Common"],
         ["Priest",0,"Spend all your Mana. Summon a random minion that costs that much.","Forbidden Shaping","Epic"],
         ["Priest",2,"This turn, your healing effects deal damage instead.","Embrace the Shadow","Epic"],
         ["Priest",4,"Destroy all minions with 2 or less Attack.","Shadow Word: Horror","Rare"],
         ["Priest",5,"Give a minion +2/+6.","Power Word: Tentacles","Common"],
         ["Rogue",1,"Discover a Deathrattle card.","Journey Below","Rare"],
         ["Rogue",3,"Deal 5 damage to an undamaged character.","Shadow Strike","Common"],
         ["Rogue",6,"Draw a card. Add 2 extra copies of it to your hand.","Thistle Tea","Rare"],
         ["Shaman",1,"Give a minion +1/+1 for each of your Totems.","Primal Fusion","Common"],
         ["Shaman",1,"Transform your minions into random minions that cost (1) more.","Evolve","Rare"],
         ["Shaman",2,"Deal 4 damage to a minion. Overload (1)","Stormcrack","Common"],
         ["Warlock",0,"Spend all your Mana. Summon that many 1/1 Tenctacles.","Forbidden Ritual","Rare"],
         ["Warlock",2,"Replace your Hero Power and Warlock cards with another class's. The cards cost(1) less.","Renounce Darkness","Epic"],
         ["Warlock",3,"Deal 9 damage randomly split among ALL characters.","Spreading Madness","Rare"],
         ["Warlock",10,"Destroy all minions. Draw a card for each.","DOOM!","Epic"],
         ["Warrior",1,"Deal 1 damage to a minion. If it survives, summon a 2/2 Slime.","Blood To Ichor","Rare"],
         ["Warrior",3,"Add a copy of each damaged friendly minion to your hand.","Blood Warriors","Epic"]
    ]
  return Cards

def Weapons():
  #[class,mana cost,attack,durability,text,name,rarity]
  Cards=[["Paladin",3,3,2,"Battlecry: Give +1/+1 to all your minions with Divine Shield.","Rallying Blade","Rare"],
         ["Shaman",5,4,2,"Deathrattle: Summon a 4/2 Elemental.","Hammer of Twilight","Epic"],
         ["Warrior",5,2,2,"Deathrattle: Return this to your hand.","Tentacles for Arms","Epic"]
    ]
  return Cards
