#Basic Set

def All():
  Cards=Minions()
  Cards+=Spells()
  Cards+=Weapons()
  return Cards

def Minions():
  #[class,mana cost,attack,health,text,tribe,name,rarity]
  Cards=[["Druid",8,8,8,"Taunt","","Ironbark Protector","Basic"],
         ["Hunter",1,1,1,"Your other Beasts have +1 Attack","Beast","Timber Wolf","Basic"],
         ["Hunter",4,4,3,"Battecry: Give a friendly Beast +2/+2 and Taunt.","","Houndmaster","Basic"],
         ["Hunter",5,3,2,"Whenever you summon a Beast, draw a card.","Beast","Starving Buzzard","Basic"],
         ["Hunter",5,2,5,"Your Beasts have Charge.","Beast","Tundra Rhino","Basic"],
         ["Mage",4,3,6,"Freeze any character damaged by this minion.","","Water Elemental","Basic"],
         ["Paladin",7,5,6,"Battlecry: Restore 6 Health to your hero.","","Guardian of Kings","Basic"],
         ["Priest",1,1,3,"Whenever a minion is healed, draw a card.","","Northshire Cleric","Basic"],
         ["Shaman",2,0,3,"Adjacent minions have +2 Attack.","Totem","Flametongue Totem","Basic"],
         ["Shaman",4,3,3,"Battlecry: Give a friendly minion Windfury","","Windspeaker","Basic"],
         ["Shaman",6,6,5,"Battlecry: Deal 3 damage.","","Fire Elemental","Basic"],
         ["Warlock",1,1,3,"Taunt.","Demon","Voidwalker","Basic"],
         ["Warlock",2,4,3,"Battlecry: Discard a random card.","Demon","Succubus","Basic"],
         ["Warlock",6,6,6,"Battlecry: Deal 1 damage to ALL other characters.","Demon","Dread Infernal","Basic"],
         ["Warrior",3,2,3,"Your Charge minions have +1 Attack.","","Warsong Commander","Basic"],
         ["Warrior",4,4,3,"Charge.","","Kor'kron Elite","Basic"],
         ["Neutral",1,1,1,"Battlecry: Deal 1 damage.","","Elven Archer","Basic"],
         ["Neutral",1,1,2,"Taunt.","","Goldshire Footman","Basic"],
         ["Neutral",1,1,1,"ALL other Murlocs have +1 Attack","Murloc","Grimscale Oracle","Basic"],
         ["Neutral",1,2,1,"","Murloc","Murloc Raider","Basic"],
         ["Neutral",1,1,1,"Charge.","Beast","Stonetusk Boar","Basic"],
         ["Neutral",1,2,1,"Battlecry: Restore 2 Health.","","Voodoo Doctor","Basic"],
         ["Neutral",2,3,2,"Battlecry: Destroy your opponent's weapon.","","Acidic Swamp Ooze","Basic"],
         ["Neutral",2,3,2,"","Beast","Bloodfen Raptor","Basic"],
         ["Neutral",2,2,1,"Charge.","Murloc","Bluegill Warrior","Basic"],
         ["Neutral",2,2,2,"Taunt.","","Frostwolf Grunt","Basic"],
         ["Neutral",2,2,2,"Spell Damage +1.","","Kobold Geomancer","Basic"],
         ["Neutral",2,2,1,"Battlecry: Summon a 1/1 Murloc Scout.","Murloc","Murloc Tidehunter","Basic"],
         ["Neutral",2,1,1,"Battlecry: Draw a card.","","Novice Engineer","Basic"],
         ["Neutral",2,2,3,"","Beast","River Crocolisk","Basic"],
         ["Neutral",3,1,4,"Spell Damage +1","","Dalaran Mage","Basic"],
         ["Neutral",3,2,2,"Battlecry: Deal 1 damage.","","Ironforge Rifleman","Basic"],
         ["Neutral",3,3,3,"Taunt","Beast","Ironfur Grizzly","Basic"],
         ["Neutral",3,5,1,"","","Magma Rager","Basic"],
         ["Neutral",3,2,2,"Your other minions have +1 Attack","","Raid Leader","Basic"],
         ["Neutral",3,2,3,"Battlecry: Summon a 1/1 Boar.","","Razorfen Hunter","Basic"],
         ["Neutral",3,3,2,"Battlecry: Give a friendly minion +1/+1.","","Shattered Sun Cleric","Basic"],
         ["Neutral",3,1,4,"Taunt","Beast","Silverback Patriarch","Basic"],
         ["Neutral",3,3,1,"Charge","","Wolfrider","Basic"],
         ["Neutral",4,4,5,"","","Chillwind Yeti","Basic"],
         ["Neutral",4,2,4,"Battlecry: Summmon a 2/1 Mechanical Dragonling.","","Dragonling Mechanic","Basic"],
         ["Neutral",4,2,4,"Battlecry: Draw a card.","","Gnomish Inventor","Basic"],
         ["Neutral",5,2,7,"","Beast","Oasis Snapjaw","Basic"],
         ["Neutral",4,4,4,"Spell Damage +1","","Ogre Magi","Basic"],
         ["Neutral",4,3,5,"Taunt","","Sen'jin Shieldmasta","Basic"],
         ["Neutral",4,2,5,"Charge","","Stormwind Knight","Basic"],
         ["Neutral",5,5,4,"Taunt","","Booty Bay Bodyguard","Basic"],
         ["Neutral",5,4,5,"Battlecry: Restore 2 Health to all friendly characters.","","Darkscale Healer","Basic"],
         ["Neutral",5,4,4,"Battlecry: Gain +1/+1 for each other friendly minion on the battlefield.","","Frostwolf Warlord","Basic"],
         ["Neutral",5,2,7,"Whenever this minion takes damage, gain +3 Attack.","","Gurubashi Berserker","Basic"],
         ["Neutral",5,4,4,"Battlecry: Deal 3 damage to the enemy hero.","","Nightblade","Basic"],
         ["Neutral",5,4,2,"Battlecry: Deal 2 damage.","","Stormpike Commando","Basic"],
         ["Neutral",6,4,7,"Spell Damage +1","","Archmage","Basic"],
         ["Neutral",6,6,7,"","","Boulderfist Ogre","Basic"],
         ["Neutral",6,6,5,"Taunt","","Lord of the Arena","Basic"],
         ["Neutral",6,5,2,"Charge","","Reckless Rocketeer","Basic"],
         ["Neutral",7,9,5,"","Beast","Core Hound","Basic"],
         ["Neutral",7,6,6,"Your other minions have +1/+1.","","Stormwind Champion","Basic"],
         ["Neutral",7,7,7,"","","War Golem","Basic"]
    ]
  return Cards

def Spells():
  #[class,mana cost,text,name,rarity]
  Cards=[["Druid",0,"Gain 2 Mana Crystals this turn only.","Innervate","Basic"],
         ["Druid",0,"Deal 1 damage.","Moonfire","Basic"],
         ["Druid",1,"Give your hero +2 Attack this turn and 2 Armor.","Claw","Basic"],
         ["Druid",2,"Give a minion Taunt and +2/+2.","Mark of the Wild","Basic"],
         ["Druid",2,"Gain an empty Mana Crystal.","Wild Growth","Basic"],
         ["Druid",3,"Restore 8 Health.","Healing Touch","Basic"],
         ["Druid",3,"Give you characters +2 Attack this turn.","Savage Roar","Basic"],
         ["Druid",4,"Deal 4 damage to an enemy and 1 damage to all other enemies.","Swipe","Basic"],
         ["Druid",6,"Deal 5 damage. Draw a card.","Starfire","Basic"],
         ["Hunter",1,"Deal 2 damage.","Arcane Shot","Basic"],
         ["Hunter",1,"Change a minion's Health to 1.","Hunter's Mark","Basic"],
         ["Hunter",1,"Look at the top three cards of your deck. Draw one and discard the others.","Tracking","Basic"],
         ["Hunter",3,"Summon a random Beast Companion.","Animal Companion","Basic"],
         ["Hunter",3,"Deal 3 damage. If you have a Beast, deal 5 damage instead.","Kill Command","Basic"],
         ["Hunter",4,"Deal 3 damage to two random enemy minions.","Multi-Shot","Basic"],
         ["Mage",1,"Deal 3 damage split among all enemies.","Arcane Missiles","Basic"],
         ["Mage",1,"Summon two 0/2 minions with Taunt.","Mirror Image","Basic"],
         ["Mage",2,"Deal 1 damage to all enemy minions.","Arcane Explosion","Basic"],
         ["Mage",2,"Deal 3 damage to a character and Freeze it.","Frostbolt","Basic"],
         ["Mage",3,"Draw 2 cards.","Arcane Intellect","Basic"],
         ["Mage",3,"Freeze all enemy miniona.","Frost Nova","Basic"],
         ["Mage",4,"Deal 6 damage.","Fireball","Basic"],
         ["Mage",4,"Transform a minion into a 1/1 Sheep.","Polymorph","Basic"],
         ["Mage",7,"Deal 4 damage to all enemy minions.","Flamestrike","Basic"],
         ["Paladin",1,"Give a minion +3 Attack.","Blessing of Might","Basic"],
         ["Paladin",1,"Give a minion Divine Shield","Hand of Protection","Basic"],
         ["Paladin",1,"Change a minion's Attack to 1.","Humility","Basic"],
         ["Paladin",2,"Restore 6 Health.","Holy Light","Basic"],
         ["Paladin",4,"Give a minion +4/+4.","Blessing of Kings","Basic"],
         ["Paladin",4,"Deal 2 damage to all enemies.","Consecration","Basic"],
         ["Paladin",4,"Deal 3 damage. Draw a card.","Hammer of Wrath","Basic"],
         ["Priest",1,"Deal 2 damage.","Holy Smite","Basic"],
         ["Priest",1,"Put a copy of a random card in your opponent's hand into your hand.","Mind Vision","Basic"],
         ["Priest",1,"Give a minion +2 Health. Draw a card.","Power Word: Shield","Basic"],
         ["Priest",2,"Double a minion's Health.","Divine Spirit","Basic"],
         ["Priest",2,"Deal 5 damage to the enemy hero.","Mind Blast","Basic"],
         ["Priest",2,"Destroy a minion with 3 or less Attack.","Shadow Word: Pain","Basic"],
         ["Priest",3,"Destroy a minion with an Attack of 5 or more.","Shadow Word: Death","Basic"],
         ["Priest",5,"Deal 2 damage to all enemies. Restore 2 Health to all friendly characters.","Holy Nova","Basic"],
         ["Priest",10,"Take control of an enemy minion.","Mind Control","Basic"],
         ["Rogue",0,"Deal 2 damage to an undamaged minion.","Backstab","Basic"],
         ["Rogue",1,"Give your weapon +2 Attack.","Deadly Poison","Basic"],
         ["Rogue",1,"Deal 3 damage to the enemy hero.","Sinister Strike","Basic"],
         ["Rogue",2,"Return an enemy minion to your opponent's hand.","Sap","Basic"],
         ["Rogue",2,"Deal 1 damage. Draw a card.","Shiv","Basic"],
         ["Rogue",3,"Deal 1 damage to all enemy minions. Draw a card.","Fan of Knives","Basic"],
         ["Rogue",5,"Destroy an enemy minion.","Assassinate","Basic"],
         ["Rogue",6,"Return all minions to their owner's hand.","Vanish","Basic"],
         ["Rogue",7,"Draw 4 cards.","Sprint","Basic"],
         ["Shaman",0,"Give your Totems +2 Health.","Totemic Might","Basic"],
         ["Shaman",0,"Restore a minion to full Health and give it Taunt.","Ancestral Healing","Basic"],
         ["Shaman",2,"Give a friendly character +3 Attack this turn.","Rockbiter Weapon","Basic"],
         ["Shaman",1,"Deal 1 damage to an enemy character and Freeze it.","Frost Shock","Basic"],
         ["Shaman",2,"Give a minion Windfury.","Windfury","Basic"],
         ["Shaman",3,"Transform a minion into a 0/1 Frog with Taunt.","Hex","Basic"],
         ["Shaman",5,"Give your minions +3 Attack this turn.","Bloodlust","Basic"],
         ["Warlock",0,"Destroy a Demon. Restore 5 Health to your hero.","Sacrificial Pact","Basic"],
         ["Warlock",1,"Deal 4 damage. Discard a random card.","Soulfire","Basic"],
         ["Warlock",1,"Deal 1 damage to a minion. If that kills it, draw a card.","Mortal Coil","Basic"],
         ["Warlock",1,"Choose an enemy minion. At the start of your turn, destroy it.","Corruption","Basic"],
         ["Warlock",3,"Deal 4 damage to a minion.","Shadow Bolt","Basic"],
         ["Warlock",3,"Deal 2 damage. Restore 2 Health to your hero.","Drain Life","Basic"],
         ["Warlock",4,"Deal 3 damage to ALL characters.","Hellfire","Basic"],
         ["Warrior",1,"Deal 1 damage to ALL minions.","Whirlwind","Basic"],
         ["Warrior",2,"Destory a damaged enemy minion.","Execute","Basic"],
         ["Warrior",2,"Give your hero +4 Attack this turn.","Herioc Strike","Basic"],
         ["Warrior",2,"Deal 2 damage to two random enemy minions.","Cleave","Basic"],
         ["Warrior",3,"Gain 5 Armor. Draw a card.","Shield Block","Basic"],
         ["Warrior",1,"Give a friendly minion Charge. It can't attack heroes this turn.","Charge","Basic"]
    ]

  return Cards

def Weapons():
  #[class,mana cost,attack,durability,text,name,rarity]
  Cards=[["Paladin",1,1,4,"","Light's Justice","Basic"],
         ["Paladin",4,4,2,"Whenever your hero attacks, restore 2 Health to it.","Truesilver Champion","Basic"],
         ["Rogue",5,3,4,"","Assassin's Blade","Basic"],
         ["Warrior",2,3,2,"","Fiery War Axe","Basic"],
         ["Warrior",5,5,2,"","Arcanite Reaper","Basic"]
    ]
  return Cards
