#Mean Streets of Gadgetzan Set

def All():
  Cards=Minions()
  Cards+=Spells()
  Cards+=Weapons()
  return Cards

def Minions():
  #[class,mana cost,attack,health,text,tribe,name,rarity]
  Cards=[["Neutral",1,1,1,"Deathrattke: Shuffle this minion into your opponent's deck.","Beast","Weasel Tunneler","Epic"],
         ["Neutral",1,1,2,"Has +2 Attack while you have a weapon equipped.","Pirate","Small-Time Buccaneer","Rare"],
         ["Neutral",1,1,1,"Charge. After you play a Pirate, summon this minion from your deck.","Pirate","Patches the Pirate","Legendary"],
         ["Neutral",1,2,2,"Deathrattle: Restore 4 Health to both players.","","Mistress of Mixtures","Common"],
         ["Paladin",1,1,2,"Deathrattle: If this minion has 2 or more Attack, draw a card.","","Meanstreet Marshal","Epic"],
         ["Mage",1,2,1,"Battlecry: The next Secret you play this turn costs (0).","","Kabal Lackey","Common"],
         ["Paladin",1,2,1,"Battlecry: Give a random Murloc in your hand +1/+1.","Murloc","Grimscale Chum","Common"],
         ["Hunter",1,1,1,"Battlecry: Summon a 1/1 Cat.","Beast","Alleycat","Common"],
         ["Hunter",2,3,2,"Battlecry: Give a random Beast in your hand +1/+1.","","Trogg Beastrager","Rare"],
         ["Warrior",2,0,7,"Taunt","","Public Defender","Common"],
         ["Priest",2,2,3,"Whenever this minion is healed, summon a 2/2 Crystal.","","Mana Geode","Epic"],
         ["Rogue",2,1,1,"Stealth, Deathrattle: Summon a Jade Golem.","","Jade Swarmer","Common"],
         ["Warrior",2,2,2,"Battlecry: Give all weapons in your hand and deck +1 Attack.","","Hobart Grapplehammer","Legendary"],
         ["Paladin",2,1,1,"Battlecry: Give all minions in your hand +1/+1.","","Grimestreet Outfitter","Common"],
         ["Neutral",2,1,1,"Battlecry: Discover a Hunter, Paladin, or Warrior card.","","Grimestreet Informant","Rare"],
         ["Neutral",2,2,2,"Battlecry: Restore 2 Health.","","Gadgetzan Socialite","Common"],
         ["Rogue",2,2,3,"Combo: Return a friendly minion to your hand.","","Gadgetzan Ferryman","Rare"],
         ["Neutral",2,2,3,"At the end of your turn, restore 1 Health to your hero.","","Friendly Bartender","Common"],
         ["Neutral",2,2,6,"Taunt. Battlecry: Your opponent summons a random minion from their hand.","","Dirty Rat","Epic"],
         ["Neutral",2,2,1,"Battlecry: Deal 1 damage.","Murloc","Blowgill Sniper","Common"],
         ["Paladin",3,2,2,"Divine Shield. Taunt. Damage dealt by this minion also heals your hero.","","Wickerflame Burnbristle","Legendary"],
         ["Warlock",3,5,5,"Whenever you summon a minion, deal 5 damage to your Hero.","Demon","Unlicensed Apothecary","Epic"],
         ["Neutral",3,4,3,"Battlecry: Remove 1 Durability from your opponent's weapon.","","Toxic Sewer Ooze","Common"],
         ["Neutral",3,0,7,"Spell Damage +1","Demon","Street Trickster","Common"],
         ["Hunter",3,3,3,"Deathrattle: Give a random minion in your hand +2/+2.","","Shaky Zipgunner","Common"],
         ["Rogue",3,2,3,"Stealth. Whenever this attacks, add a random card to your hand (from your opponent's class).","","Shaku, the Collector","Legendary"],
         ["Rogue",3,5,1,"Stealth","","Shadow Rager","Common"],
         ["Neutral",3,1,1,"Deathrattle: deal damage equal to this minion's Attack to all enemy minions.","","Sergeant Sally","Legendary"],
         ["Hunter",3,2,2,"Deathrattle: Summon a number of 1/1 Rats equal to this minion's Attack.","Beast","Rat Pack","Epic"],
         ["Mage",3,3,4,"Battlecry: Choose a friendly minion. Shuffle a copy into your deck.","","Manic Soulcaster","Epic"],
         ["Priest",3,3,4,"Battlecry: Give a friendly minion +3 Health.","","Kabal Talonpriest","Common"],
         ["Neutral",3,2,2,"Battlecry: Discover a Mage, Priest, or Warlock card.","","Kabal Courier","Rare"],
         ["Neutral",3,4,2,"Taunt","","Hired Gun","Common"],
         ["Neutral",3,2,4,"Battlecry: Give a random minion in your hand +1/+1.","","Grimestreet Smuggler","Common"],
         ["Warrior",3,3,3,"Battlecry: Give a random weapon in your hand +1/+1.","","Grimestreet Pawnbroker","Rare"],
         ["Neutral",3,3,7,"At the start of your turn, deal 2 damage to this minion.","","Fel Orc Soulfiend","Epic"],
         ["Druid",3,3,3,"Battlecry: If a friendly minion has 5 or more Attack, gain +2/+2.","","Celestial Dreamer","Rare"],
         ["Neutral",3,1,1,"Whenever you summon a Battlecry minion while this is in your hand, gain +1/+1.","","Blubber Baron","Epic"],
         ["Neutral",3,3,1,"Deathrattle: Deal 2 damage to the enemy hero.","","Backstreet Leper","Common"],
         ["Neutral",3,3,4,"After you cast a spell, refresh your Hero Power.","","Auctionmaster Beardo","Legendary"],
         ["Neutral",4,6,3,"","","Worgen Greaser","Common"],
         ["Neutral",4,4,4,"Battlecry: If your opponent's hand is empty, gain Charge.","","Tanaris Hogchopper","Common"],
         ["Rogue",4,4,4,"Battlecry: Give a Stealthed minion +2/+2.","","Shadow Sensei","Rare"],
         ["Warlock",4,4,2,"Battlecry: The next Murlco you play this turn costs Health instead of Mana.","Murloc","Seadevil Stinger","Rare"],
         ["Neutral",4,5,4,"Battlecry: Give your weapon +1 Attack.","Pirate","Naga Corsair","Common"],
         ["Shaman",4,3,5,"After this minion attacks a hero, transform it into a random 6-Cost minion.","","Lotus Illusionist","Epic"],
         ["Neutral",4,4,4,"Battlecry: Swap the Attack and Health of a minion.","","Kooky Chemist","Common"],
         ["Neutral",4,3,3,"Battlecry: If your deck contains no duplicates, create a custom spell.","","Kazakus","Legendary"],
         ["Neutral",4,3,3,"Battlecry: Add a random Potion to your hand.","","Kabal Chemist","Common"],
         ["Shaman",4,3,6,"Battlecry: Restore 6 Health. Overload (1)","","Jinyu Waterspeaker","Rare"],
         ["Neutral",4,2,3,"Battlecry: Summon a Jade Golem.","","Jade Spirit","Common"],
         ["Neutral",4,2,6,"Battlecry: Restore a minion to full Health.","","Hozen Healer","Common"],
         ["Warrior",4,4,3,"At the end of your turn, give a random minion in your hand +2/+2.","","Grimy Gadgeteer","Common"],
         ["Neutral",4,5,4,"Whenever this attacks both players draw until they have 3 cards.","","Genzo, the Shark","Legendary"],
         ["Hunter",4,2,4,"Battlecry: Deal damage equal to this minion's Attack.","Beast","Dispatch Kodo","Rare"],
         ["Neutral",4,3,3,"Whenever your opponent draws a card, gain +1/+1.","","Daring Reporter","Common"],
         ["Warlock",4,5,4,"Battlecry: Give your Demons +1/+1.","","Crystalweaver","Common"],
         ["Neutral",4,4,4,"Whenever a friendly minion dies, gain +1 Attack.","","Backroom Bouncer","Rare"],
         ["Shaman",5,5,5,"Taunt. Deathrattle: Shuffle 'The Storm Guardian' into your deck.","","White Eyes","Legendary"],
         ["Druid",5,4,5,"Battlecry: Give a friendly Beast +2/+2.","","Virmen Sensei","Rare"],
         ["Priest",5,5,5,"Battlecry: If your deck has no dupicates, your Hero Power costs(0) this game.","","Raza the Chained","Legendary"],
         ["Rogue",5,5,5,"Stealth. Whenever this attacks and kills a minion, gain Stealth.","","Lotus Assassin","Epic"],
         ["Neutral",5,5,3,"Battlecry: Discover a Druid, Rogue or Shaman card.","","Lotus Agents","Rare"],
         ["Hunter",5,3,7,"After this attacks a minion, it also hits the enemy hero.","Beast","Knuckles","Legendary"],
         ["Priest",5,5,5,"Battlecry: Silence a minion.","","Kabal Songstealer","Common"],
         ["Neutral",5,3,5,"Windfury","","Grook Fu Master","Common"],
         ["Paladin",5,4,4,"At the end of your turn, give all minions in your hand +1/+1.","","Grimestreet Enforcer","Rare"],
         ["Neutral",5,2,4,"Stealth. Whenever this attacks and kills a minion, summon 2 Murlocs from your deck.","Murloc","Finja, the Flying Star","Legendary"],
         ["Priest",5,5,6,"Battlecry: If you're holding a Dragon, Discover a card in your opponent's deck.","Dragon","Drakonoid Operative","Rare"],
         ["Neutral",5,2,2,"Battlecry: Summon 2 copies of this minion.","","Doppelgangster","Rare"],
         ["Mage",5,5,5,"Battlecry: Gain +2/+2 if an enemy is Frozen.","","Cryomancer","Common"],
         ["Neutral",5,4,6,"Whenever your opponent casts a spell, add a Coin to your hand.","","Burgly Bully","Epic"],
         ["Neutral",5,2,2,"Battlecry: Deal 5 damage to an enemy minion. Deathrattle: Deal 5 damage to your hero.","","Bomb Squad","Rare"],
         ["Warrior",5,2,7,"Taunt. Whenever this minion deals damage, gain that much Armor.","","Alley Armorsmith","Rare"],
         ["Neutral",6,4,5,"Taunt. Battlecry: Draw cards until you draw one that isn't a Dragon.","","Wrathion","Legendary"],
         ["Neutral",6,5,5,"Whenever this attacks a minion and survives, draw a card.","Mech","Wind-up Burglerbot","Epic"],
         ["Neutral",6,4,3,"Battlecry: Choose a friendly minion. Swap it with a minion in your deck.","","Madam Goya","Legendary"],
         ["Rogue",6,5,5,"Battlecry: If your weapon has at least 3 Attack, gain +4/+4.","Pirate","Luckydo Buccaneer","Epic"],
         ["Neutral",6,6,6,"Battlecry: If your opponent has 6 or more cards in hand, gain Charge.","","Leatherclad Hogleader","Epic"],
         ["Warlock",6,6,6,"At the end of your turn, add a random Demon to your hand.","","Kabal Trafficker","Epic"],
         ["Mage",6,5,5,"Costs (2) less for each Secret you've played this game.","","Kabal Crystal Runner","Rare"],
         ["Druid",6,3,6,"Taunt. Battlecry: Summon a Jade Golem.","","Jade Behemoth","Common"],
         ["Neutral",6,4,4,"Battlecry: If you control a minion with 6 or more Health, draw two cards.","","Fight Promoter","Epic"],
         ["Neutral",6,5,7,"Battlecry: Silence a minion with Deathrattle.","","Defias Cleaner","Epic"],
         ["Neutral",6,1,1,"Battlecry: Summon a 6/6 Ogre.","","Big-Time Racketeer","Common"],
         ["Neutral",6,5,3,"Battlecry and Deathrattle: Summon a Jade Golem.","","Aya Blackpaw","Legendary"],
         ["Neutral",6,3,8,"Taunt","","Ancient of Blossoms","Common"],
         ["Shaman",7,5,5,"Battlecry: Summon a Jade Golem. Give it Taunt.","","Jade Chieftain","Common"],
         ["Mage",7,5,5,"Battlecry: If your deck has no duplicates, the next spell you cast this turn costs (0).","","Inkmaster Solia","Legendary"],
         ["Paladin",7,6,6,"Taunt. Battlecry: Give adjacent minions Divine Shield.","","Grimestreet Protector","Rare"],
         ["Neutral",7,5,6,"Battlecry: Give a random minion in your hand +5/+5.","","Don Han'Cho","Legendary"],
         ["Warlock",7,6,6,"Battlecry: Deal 3 damage to all other characters.","Demon","Abyssal Enforcer","Common"],
         ["Neutral" ,9,5,4,"All targets are chosen randomly.","","Mayor Noggenfogger","Legendary"],
         ["Warlock",9,7,9,"Battlecry: If your deck has no duplicates, summon all Demons from your hand.","Demon","Krul the Unshackled","Legendary"],
         ["Druid",10,7,7,"Choose One- Gain 10 Armor; or Refresh your Mana Crystals.","","Kun the Forgotten King","Legendary"]

    ]
  return Cards

def Spells():
  #[class,mana cost,text,name,rarity]
  Cards=[["Mage",0,"Freeze an enemy","Freezing Potion","Common"],
         ["Rogue",0,"Gain 1 Mana Crystal this turn only.","Counterfeit Coin","Rare"],
         ["Paladin",1,"Give all minions in your hand +1/+1.","Smuggler's Run","Common"],
         ["Hunter",1,"Give a random Beast in your hand +2/+2.","Smuggler's Crate","Common"],
         ["Priest",1,"Gain control of an enemy minion with 2 or less Attack until end of turn.","Potion of Madness","Common"],
         ["Priest",1,"Give all enemy minions -3 Attack this turn only.","Pint-Size Potion","Rare"],
         ["Druid",1,"Give your minions +1/+1.","Mark of the Lotus","Common"],
         ["Druid",1,"Choose One- Summon a Jade Golem; or Shuffle 3 copies of this card into your deck.","Jade Idol","Rare"],
         ["Warrior",1,"Discover a Taunt minion.","I Know a Guy","Common"],
         ["Paladin",1,"Secret: When a friendly minion dies, return it to your hand.","Getaway Kodo","Rare"],
         ["Shaman",1,"Discover a card with Overload. Overload: (1).","Finders Keepers","Epic"],
         ["Warrior",2,"Give a random Taunt minion in your hand +3/+3.","Stolen Goods","Rare"],
         ["Warrior",2,"Deal 3 damage to all damaged minions.","Sleep with the Fishes","Epic"],
         ["Rogue",2,"Deal 2 damage. Combo: Summon a Jade Golem.","Jade Shuriken","Common"],
         ["Hunter",2,"Secret: After your opponent plays a minion, give a random minion in your hand +2/+2.","Hidden Cache","Rare"],
         ["Shaman",2,"Transform all enemy minions into random ones that cost (1) less.","Devolve","Rare"],
         ["Mage",3,"Deal 2 damage to all minions.","Volcanic Potion","Rare"],
         ["Paladin",3,"Draw three 1-Cost minions from your deck.","Small-Time Recruits","Epic"],
         ["Mage",3,"Secret: After your opponent plays a minion, transform it into a 1/1 Sheep.","Potion of Polymorph","Rare"],
         ["Druid",3,"Gain an empty Mana Crystal for each friendly minion.","Pilfered Power","Epic"],
         ["Druid",3,"Summon a Jade Golem. Gain an empty Mana Crystal.","Jade Blossom","Common"],
         ["Warlock",3,"Give a minion +3 Attack. If it's a Demon, also give it +3 Health.","Bloodfury Potion","Rare"],
         ["Shaman",4,"Deal 4 damage. Summon a Jade Golem.","Jade Lightning","Common"],
         ["Priest",4,"Restore 12 Health to a friendly character.","Greater Healing Potion","Rare"],
         ["Shaman",4,"Summon four 1/1 Murlocs.","Call in the Finishers","Common"],
         ["Warlock",4,"Destroy a minion and one of your Mana Crystals.","Blastcrystal Potion","Common"],
         ["Druid",5,"Draw 2 cards. Minions drawn cost (2) less.","Lunar Visions","Epic"],
         ["Warlock",6,"Deal 5 damage to all characters.","Felfire Potion","Rare"],
         ["Priest",6,"Deal 5 damage to all minions except Dragons.","Dragonfire Potion","Epic"],
         ["Mage",7,"Shoot three missiles at random enemies that deal 3 damage each.","Greater Arcane Missiles","Epic"]
    ]
  return Cards

def Weapons():
  #[class,mana cost,attack,durability,text,name,rarity]
  Cards=[["Hunter",5,2,4,"After your hero attacks, summon a 1/1 Piranha.","Piranha Launcher","Epic"],
         ["Warrior",4,2,3,"After your hero attacks, give a random minion in your hand +1/+1.","Brass Knuckles","Epic"],
         ["Shaman",2,2,2,"Battlecry: Summon a Jade Golem. Overload: (1)","Jade Claws","Rare"]
    ]
  return Cards
